
    Add the following to your site's _config.yml:

    remote_theme: pages-themes/hacker@v0.2.0
    #plugins:
    #- jekyll-remote-theme # add this line to the plugins list if you already have one

    #    Optionally, if you'd like to preview your site on your computer, add the following to your site's Gemfile:

    gem "github-pages", group: :jekyll_plugins